# Generated by Django 5.1.3 on 2024-11-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('opportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('professor_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('eligibility_criteria', models.TextField()),
                ('required_skills', models.TextField()),
                ('application_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
