# Generated by Django 5.1.1 on 2024-11-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_address_remove_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, default='', null=True, upload_to='resumes/'),
        ),
    ]
