# Generated by Django 5.1.3 on 2024-12-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0028_alter_student_application_research_opportunity_and_more'),
        ('students', '0007_student_applied_at_student_resume_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('research_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='professor.researchopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='students.student')),
            ],
        ),
    ]
