# Generated by Django 5.1.3 on 2024-12-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='resume_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/'),
        ),
    ]
