# Generated by Django 5.1.3 on 2024-12-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentapplication_resume_score_alter_student_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
