# Generated by Django 5.1.1 on 2024-11-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_resume'),
        ('students', '0005_student_address_student_certifications_and_more'),
    ]

    operations = [
    ]
