# Generated by Django 5.1.2 on 2024-10-19 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchopportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('research_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.student')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.resume')),
            ],
        ),
    ]
