# Generated by Django 5.1.1 on 2024-11-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coistaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='user',
        ),
    ]
