# Generated by Django 5.1.2 on 2024-10-21 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='professors_pics/')),
                ('publications', models.TextField(blank=True, null=True)),
                ('posted_opportunities_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('research_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('max_applications', models.IntegerField(default=10)),
                ('current_applications', models.IntegerField(default=0)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_opportunities', to='professor.professor')),
            ],
        ),
    ]
