# Generated by Django 5.1.2 on 2024-10-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
