# Generated by Django 5.1.2 on 2024-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_first_name_professor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
