# Generated by Django 5.1.1 on 2024-10-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_first_name_professor_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
