# Generated by Django 5.1.1 on 2024-11-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0017_professor_email_professor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
