# Generated by Django 5.1.1 on 2024-11-25 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0018_alter_professor_password'),
        ('students', '0002_remove_student_address_remove_student_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('research_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='professor.researchopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
            ],
        ),
    ]
