# Generated by Django 5.1.1 on 2024-11-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0019_application'),
        ('students', '0003_alter_student_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Student_Application',
        ),
    ]
