# Generated by Django 5.1.1 on 2024-11-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0020_rename_application_student_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
