# Generated by Django 5.1.3 on 2024-11-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0021_student_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='password',
            new_name='password1',
        ),
    ]
