# Generated by Django 5.1.1 on 2024-11-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0022_professor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='username',
        ),
    ]
