# Generated by Django 5.1.3 on 2024-11-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0022_rename_password_professor_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='password1',
            new_name='password',
        ),
    ]
