# Generated by Django 5.1.3 on 2024-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0023_rename_password1_professor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/'),
        ),
    ]
