# Generated by Django 5.1.3 on 2024-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0024_student_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_application',
            name='resume_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
