# Generated by Django 5.1.3 on 2024-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0025_student_application_resume_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_application',
            name='resume_score',
        ),
        migrations.RemoveField(
            model_name='student_application',
            name='status',
        ),
    ]
