# Generated by Django 5.1.3 on 2024-12-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0026_resumescore_remove_student_application_resume_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
