# Generated by Django 5.1.1 on 2024-12-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0028_remove_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchopportunity',
            name='short_description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
