# Generated by Django 5.1.3 on 2024-12-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0028_alter_student_application_research_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_application',
            name='resume_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
