# Generated by Django 5.1.1 on 2024-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0029_researchopportunity_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/'),
        ),
    ]
