# Generated by Django 5.1.3 on 2024-12-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0029_student_application_resume_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeScore',
        ),
    ]
