# Generated by Django 5.1.1 on 2024-12-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0030_student_application_resume'),
        ('students', '0007_student_applied_at_student_resume_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Application_For_Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('research_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='professor.researchopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications_for_professors', to='students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Application',
        ),
    ]
