# Generated by Django 5.1.1 on 2024-12-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0031_student_application_for_professor_and_more'),
        ('students', '0009_alter_student_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Application_For_Professor',
            new_name='StudentApplication',
        ),
    ]
