# Generated by Django 5.1.1 on 2024-12-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0032_rename_student_application_for_professor_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
