# Generated by Django 5.1.1 on 2024-12-04 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0033_studentapplication_status'),
        ('students', '0010_studentapplication_resume_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='COIStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('position', models.CharField(default='COI Staff', max_length=100)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='coi_staff_pics/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('managed_departments', models.TextField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoiDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_unt_id', models.FileField(blank=True, null=True, upload_to='coi_documents/student_ids/')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='coi_documents/transcripts/')),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='coi_documents/recommendation_letters/')),
                ('onboarding_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_documents', to='professor.researchopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_documents', to='students.student')),
            ],
        ),
    ]
