# Generated by Django 5.1.3 on 2024-12-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coi_staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coistaff',
            name='created_by',
        ),
    ]
