# Generated by Django 5.1.3 on 2024-12-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coi_staff', '0002_remove_coistaff_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coistaff',
            name='last_login',
        ),
    ]
