# Generated by Django 5.1.3 on 2024-12-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi_staff', '0004_coidocuments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coidocuments',
            old_name='student_uni_id',
            new_name='student_unt_id',
        ),
        migrations.RemoveField(
            model_name='coidocuments',
            name='consent_form',
        ),
        migrations.RemoveField(
            model_name='coidocuments',
            name='nda',
        ),
        migrations.AddField(
            model_name='coidocuments',
            name='consent_form_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coidocuments',
            name='nda_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
