# Generated by Django 5.1.3 on 2024-12-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi_staff', '0005_rename_student_uni_id_coidocuments_student_unt_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coidocuments',
            old_name='consent_form_text',
            new_name='consent_form',
        ),
        migrations.RemoveField(
            model_name='coidocuments',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='coidocuments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coidocuments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
