# Generated by Django 5.1.3 on 2024-12-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coi_staff', '0006_rename_consent_form_text_coidocuments_consent_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coidocuments',
            old_name='status',
            new_name='onboarding_status',
        ),
    ]
